import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Clear existing data (optional - comment out if you want to keep existing data)
  await prisma.attemptExercise.deleteMany();
  await prisma.attempt.deleteMany();
  await prisma.exercise.deleteMany();
  await prisma.lesson.deleteMany();
  await prisma.unit.deleteMany();
  await prisma.course.deleteMany();

  // Create course
  const course = await prisma.course.create({
    data: {
      id: 'course_spanish_101',
      title: 'Spanish for Beginners',
      description: 'Learn the basics of Spanish',
      language: 'Spanish',
      units: {
        create: [
          {
            id: 'unit_1',
            title: 'Unit 1: Greetings & Basics',
            description: 'Learn how to greet people and introduce yourself',
            order: 1,
            lessons: {
              create: [
                {
                  id: 'lesson_1_1',
                  title: 'Greetings',
                  description: 'Learn basic greetings',
                  order: 1,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      {
                        id: 'ex_1_1_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Good morning',
                        optionsJson: JSON.stringify(['Buenos días', 'Buenas noches', 'Gracias', 'Por favor']),
                        answer: 'Buenos días',
                        explanation: "'Buenos días' is used in the morning.",
                      },
                      {
                        id: 'ex_1_1_2',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Hello',
                        optionsJson: JSON.stringify(['Hola', 'Adiós', 'Gracias', 'De nada']),
                        answer: 'Hola',
                        explanation: "'Hola' means hello in Spanish.",
                      },
                      {
                        id: 'ex_1_1_3',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: '___ días (Good morning)',
                        optionsJson: JSON.stringify([]),
                        answer: 'Buenos',
                        explanation: "'Buenos días' means good morning.",
                      },
                      {
                        id: 'ex_1_1_4',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Goodbye',
                        optionsJson: JSON.stringify(['Hola', 'Adiós', 'Buenos días', 'Gracias']),
                        answer: 'Adiós',
                        explanation: "'Adiós' means goodbye.",
                      },
                      {
                        id: 'ex_1_1_5',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: '¿Cómo estás? (How are ___)',
                        optionsJson: JSON.stringify([]),
                        answer: 'you',
                        explanation: "'¿Cómo estás?' means 'How are you?'",
                      },
                      {
                        id: 'ex_1_1_6',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Thank you',
                        optionsJson: JSON.stringify(['Por favor', 'Gracias', 'De nada', 'Hola']),
                        answer: 'Gracias',
                        explanation: "'Gracias' means thank you.",
                      },
                      {
                        id: 'ex_1_1_7',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Mucho ___ (Nice to meet you)',
                        optionsJson: JSON.stringify([]),
                        answer: 'gusto',
                        explanation: "'Mucho gusto' means nice to meet you.",
                      },
                      {
                        id: 'ex_1_1_8',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Please',
                        optionsJson: JSON.stringify(['Gracias', 'Por favor', 'De nada', 'Adiós']),
                        answer: 'Por favor',
                        explanation: "'Por favor' means please.",
                      },
                    ],
                  },
                },
                {
                  id: 'lesson_1_2',
                  title: 'Introductions',
                  description: 'Learn how to introduce yourself',
                  order: 2,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      {
                        id: 'ex_1_2_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'My name is',
                        optionsJson: JSON.stringify(['Me llamo', 'Te llamas', 'Se llama', 'Nos llamamos']),
                        answer: 'Me llamo',
                        explanation: "'Me llamo' means 'My name is'.",
                      },
                      {
                        id: 'ex_1_2_2',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Me ___ Juan (My name is Juan)',
                        optionsJson: JSON.stringify([]),
                        answer: 'llamo',
                        explanation: "'Me llamo' means 'My name is'.",
                      },
                      {
                        id: 'ex_1_2_3',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'What is your name?',
                        optionsJson: JSON.stringify(['¿Cómo te llamas?', '¿Cómo estás?', '¿Qué tal?', '¿De dónde eres?']),
                        answer: '¿Cómo te llamas?',
                        explanation: "'¿Cómo te llamas?' means 'What is your name?'",
                      },
                      {
                        id: 'ex_1_2_4',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Soy de ___ (I am from)',
                        optionsJson: JSON.stringify([]),
                        answer: 'España',
                        explanation: "'Soy de' means 'I am from'. España is Spain.",
                      },
                      {
                        id: 'ex_1_2_5',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Where are you from?',
                        optionsJson: JSON.stringify(['¿De dónde eres?', '¿Dónde vives?', '¿Cómo estás?', '¿Qué tal?']),
                        answer: '¿De dónde eres?',
                        explanation: "'¿De dónde eres?' means 'Where are you from?'",
                      },
                      {
                        id: 'ex_1_2_6',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Tengo ___ años (I am ___ years old)',
                        optionsJson: JSON.stringify([]),
                        answer: 'veinte',
                        explanation: "'Tengo' means 'I have'. 'Tengo veinte años' means 'I am twenty years old'.",
                      },
                      {
                        id: 'ex_1_2_7',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Nice to meet you',
                        optionsJson: JSON.stringify(['Mucho gusto', 'Hasta luego', 'Buenos días', 'Gracias']),
                        answer: 'Mucho gusto',
                        explanation: "'Mucho gusto' means 'Nice to meet you'.",
                      },
                      {
                        id: 'ex_1_2_8',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Encantado de ___ (Pleased to meet you)',
                        optionsJson: JSON.stringify([]),
                        answer: 'conocerte',
                        explanation: "'Encantado de conocerte' means 'Pleased to meet you'.",
                      },
                    ],
                  },
                },
                {
                  id: 'lesson_1_3',
                  title: 'Numbers 1-10',
                  description: 'Learn numbers from one to ten',
                  order: 3,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      {
                        id: 'ex_1_3_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'One',
                        optionsJson: JSON.stringify(['Uno', 'Dos', 'Tres', 'Cuatro']),
                        answer: 'Uno',
                      },
                      {
                        id: 'ex_1_3_2',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Five',
                        optionsJson: JSON.stringify(['Cuatro', 'Cinco', 'Seis', 'Siete']),
                        answer: 'Cinco',
                      },
                      {
                        id: 'ex_1_3_3',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Tres más dos es ___ (Three plus two is five)',
                        optionsJson: JSON.stringify([]),
                        answer: 'cinco',
                      },
                      {
                        id: 'ex_1_3_4',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Ten',
                        optionsJson: JSON.stringify(['Ocho', 'Nueve', 'Diez', 'Once']),
                        answer: 'Diez',
                      },
                      {
                        id: 'ex_1_3_5',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Siete menos dos es ___ (Seven minus two is five)',
                        optionsJson: JSON.stringify([]),
                        answer: 'cinco',
                      },
                      {
                        id: 'ex_1_3_6',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Eight',
                        optionsJson: JSON.stringify(['Seis', 'Siete', 'Ocho', 'Nueve']),
                        answer: 'Ocho',
                      },
                      {
                        id: 'ex_1_3_7',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Dos por cuatro es ___ (Two times four is eight)',
                        optionsJson: JSON.stringify([]),
                        answer: 'ocho',
                      },
                      {
                        id: 'ex_1_3_8',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Nine',
                        optionsJson: JSON.stringify(['Siete', 'Ocho', 'Nueve', 'Diez']),
                        answer: 'Nueve',
                      },
                    ],
                  },
                },
                {
                  id: 'lesson_1_4',
                  title: 'Common Phrases',
                  description: 'Learn common everyday phrases',
                  order: 4,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      {
                        id: 'ex_1_4_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'How are you?',
                        optionsJson: JSON.stringify(['¿Cómo estás?', '¿Qué tal?', '¿Cómo te llamas?', '¿De dónde eres?']),
                        answer: '¿Cómo estás?',
                      },
                      {
                        id: 'ex_1_4_2',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Estoy ___ (I am fine)',
                        optionsJson: JSON.stringify([]),
                        answer: 'bien',
                      },
                      {
                        id: 'ex_1_4_3',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Excuse me',
                        optionsJson: JSON.stringify(['Perdón', 'Gracias', 'Por favor', 'De nada']),
                        answer: 'Perdón',
                      },
                      {
                        id: 'ex_1_4_4',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Lo ___ (I am sorry)',
                        optionsJson: JSON.stringify([]),
                        answer: 'siento',
                      },
                      {
                        id: 'ex_1_4_5',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: "You're welcome",
                        optionsJson: JSON.stringify(['Gracias', 'De nada', 'Por favor', 'Perdón']),
                        answer: 'De nada',
                      },
                      {
                        id: 'ex_1_4_6',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'No hay de ___ (You are welcome)',
                        optionsJson: JSON.stringify([]),
                        answer: 'qué',
                      },
                      {
                        id: 'ex_1_4_7',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'See you later',
                        optionsJson: JSON.stringify(['Hasta luego', 'Hasta mañana', 'Adiós', 'Nos vemos']),
                        answer: 'Hasta luego',
                      },
                      {
                        id: 'ex_1_4_8',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Hasta ___ (See you tomorrow)',
                        optionsJson: JSON.stringify([]),
                        answer: 'mañana',
                      },
                    ],
                  },
                },
                {
                  id: 'lesson_1_5',
                  title: 'Practice: Review',
                  description: 'Review what you learned',
                  order: 5,
                  xpReward: 20,
                  type: 'practice',
                  exercises: {
                    create: [
                      {
                        id: 'ex_1_5_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Good morning',
                        optionsJson: JSON.stringify(['Buenos días', 'Buenas noches', 'Buenas tardes', 'Hola']),
                        answer: 'Buenos días',
                      },
                      {
                        id: 'ex_1_5_2',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Me ___ María (My name is María)',
                        optionsJson: JSON.stringify([]),
                        answer: 'llamo',
                      },
                      {
                        id: 'ex_1_5_3',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Thank you very much',
                        optionsJson: JSON.stringify(['Muchas gracias', 'De nada', 'Por favor', 'Perdón']),
                        answer: 'Muchas gracias',
                      },
                      {
                        id: 'ex_1_5_4',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: '¿Cómo ___? (How are you?)',
                        optionsJson: JSON.stringify([]),
                        answer: 'estás',
                      },
                      {
                        id: 'ex_1_5_5',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Nice to meet you',
                        optionsJson: JSON.stringify(['Mucho gusto', 'Hasta luego', 'Buenos días', 'Gracias']),
                        answer: 'Mucho gusto',
                      },
                      {
                        id: 'ex_1_5_6',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Soy de ___ (I am from Mexico)',
                        optionsJson: JSON.stringify([]),
                        answer: 'México',
                      },
                      {
                        id: 'ex_1_5_7',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'See you later',
                        optionsJson: JSON.stringify(['Hasta luego', 'Hasta mañana', 'Adiós', 'Nos vemos']),
                        answer: 'Hasta luego',
                      },
                      {
                        id: 'ex_1_5_8',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Tengo ___ años (I am twenty years old)',
                        optionsJson: JSON.stringify([]),
                        answer: 'veinte',
                      },
                    ],
                  },
                },
              ],
            },
          },
          {
            id: 'unit_2',
            title: 'Unit 2: Food & Drinks',
            description: 'Learn vocabulary for food and drinks',
            order: 2,
            lessons: {
              create: [
                {
                  id: 'lesson_2_1',
                  title: 'Food Basics',
                  description: 'Learn basic food vocabulary',
                  order: 1,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      {
                        id: 'ex_2_1_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Bread',
                        optionsJson: JSON.stringify(['Pan', 'Agua', 'Leche', 'Queso']),
                        answer: 'Pan',
                      },
                      {
                        id: 'ex_2_1_2',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Water',
                        optionsJson: JSON.stringify(['Pan', 'Agua', 'Leche', 'Queso']),
                        answer: 'Agua',
                      },
                      {
                        id: 'ex_2_1_3',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Quiero ___ (I want bread)',
                        optionsJson: JSON.stringify([]),
                        answer: 'pan',
                      },
                      {
                        id: 'ex_2_1_4',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Milk',
                        optionsJson: JSON.stringify(['Pan', 'Agua', 'Leche', 'Queso']),
                        answer: 'Leche',
                      },
                      {
                        id: 'ex_2_1_5',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Necesito ___ (I need water)',
                        optionsJson: JSON.stringify([]),
                        answer: 'agua',
                      },
                      {
                        id: 'ex_2_1_6',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Cheese',
                        optionsJson: JSON.stringify(['Pan', 'Agua', 'Leche', 'Queso']),
                        answer: 'Queso',
                      },
                      {
                        id: 'ex_2_1_7',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Me gusta el ___ (I like cheese)',
                        optionsJson: JSON.stringify([]),
                        answer: 'queso',
                      },
                      {
                        id: 'ex_2_1_8',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Egg',
                        optionsJson: JSON.stringify(['Huevo', 'Carne', 'Pescado', 'Pollo']),
                        answer: 'Huevo',
                      },
                    ],
                  },
                },
                {
                  id: 'lesson_2_2',
                  title: 'Fruits & Vegetables',
                  description: 'Learn fruits and vegetables',
                  order: 2,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      {
                        id: 'ex_2_2_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Apple',
                        optionsJson: JSON.stringify(['Manzana', 'Plátano', 'Naranja', 'Uva']),
                        answer: 'Manzana',
                      },
                      {
                        id: 'ex_2_2_2',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Banana',
                        optionsJson: JSON.stringify(['Manzana', 'Plátano', 'Naranja', 'Uva']),
                        answer: 'Plátano',
                      },
                      {
                        id: 'ex_2_2_3',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Me gusta la ___ (I like the apple)',
                        optionsJson: JSON.stringify([]),
                        answer: 'manzana',
                      },
                      {
                        id: 'ex_2_2_4',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Orange',
                        optionsJson: JSON.stringify(['Manzana', 'Plátano', 'Naranja', 'Uva']),
                        answer: 'Naranja',
                      },
                      {
                        id: 'ex_2_2_5',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Quiero un ___ (I want a banana)',
                        optionsJson: JSON.stringify([]),
                        answer: 'plátano',
                      },
                      {
                        id: 'ex_2_2_6',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Tomato',
                        optionsJson: JSON.stringify(['Tomate', 'Lechuga', 'Zanahoria', 'Papa']),
                        answer: 'Tomate',
                      },
                      {
                        id: 'ex_2_2_7',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Necesito ___ (I need tomatoes)',
                        optionsJson: JSON.stringify([]),
                        answer: 'tomates',
                      },
                      {
                        id: 'ex_2_2_8',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Carrot',
                        optionsJson: JSON.stringify(['Tomate', 'Lechuga', 'Zanahoria', 'Papa']),
                        answer: 'Zanahoria',
                      },
                    ],
                  },
                },
                {
                  id: 'lesson_2_3',
                  title: 'Meals',
                  description: 'Learn meal vocabulary',
                  order: 3,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      {
                        id: 'ex_2_3_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Breakfast',
                        optionsJson: JSON.stringify(['Desayuno', 'Almuerzo', 'Cena', 'Merienda']),
                        answer: 'Desayuno',
                      },
                      {
                        id: 'ex_2_3_2',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Lunch',
                        optionsJson: JSON.stringify(['Desayuno', 'Almuerzo', 'Cena', 'Merienda']),
                        answer: 'Almuerzo',
                      },
                      {
                        id: 'ex_2_3_3',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Voy a ___ (I am going to breakfast)',
                        optionsJson: JSON.stringify([]),
                        answer: 'desayunar',
                      },
                      {
                        id: 'ex_2_3_4',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Dinner',
                        optionsJson: JSON.stringify(['Desayuno', 'Almuerzo', 'Cena', 'Merienda']),
                        answer: 'Cena',
                      },
                      {
                        id: 'ex_2_3_5',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: '¿Qué quieres para el ___? (What do you want for lunch?)',
                        optionsJson: JSON.stringify([]),
                        answer: 'almuerzo',
                      },
                      {
                        id: 'ex_2_3_6',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'I am hungry',
                        optionsJson: JSON.stringify(['Tengo hambre', 'Tengo sed', 'Tengo frío', 'Tengo calor']),
                        answer: 'Tengo hambre',
                      },
                      {
                        id: 'ex_2_3_7',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Tengo ___ (I am thirsty)',
                        optionsJson: JSON.stringify([]),
                        answer: 'sed',
                      },
                      {
                        id: 'ex_2_3_8',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'I want to eat',
                        optionsJson: JSON.stringify(['Quiero comer', 'Quiero beber', 'Quiero dormir', 'Quiero estudiar']),
                        answer: 'Quiero comer',
                      },
                    ],
                  },
                },
                {
                  id: 'lesson_2_4',
                  title: 'Ordering Food',
                  description: 'Learn how to order food',
                  order: 4,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      {
                        id: 'ex_2_4_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'I would like',
                        optionsJson: JSON.stringify(['Quisiera', 'Quiero', 'Necesito', 'Tengo']),
                        answer: 'Quisiera',
                      },
                      {
                        id: 'ex_2_4_2',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: '___ un café, por favor (I would like a coffee, please)',
                        optionsJson: JSON.stringify([]),
                        answer: 'Quisiera',
                      },
                      {
                        id: 'ex_2_4_3',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'The check, please',
                        optionsJson: JSON.stringify(['La cuenta, por favor', 'El menú, por favor', 'La mesa, por favor', 'El plato, por favor']),
                        answer: 'La cuenta, por favor',
                      },
                      {
                        id: 'ex_2_4_4',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: '¿Me puede traer el ___? (Can you bring me the menu?)',
                        optionsJson: JSON.stringify([]),
                        answer: 'menú',
                      },
                      {
                        id: 'ex_2_4_5',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Table',
                        optionsJson: JSON.stringify(['Mesa', 'Silla', 'Plato', 'Vaso']),
                        answer: 'Mesa',
                      },
                      {
                        id: 'ex_2_4_6',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Una ___ para dos, por favor (A table for two, please)',
                        optionsJson: JSON.stringify([]),
                        answer: 'mesa',
                      },
                      {
                        id: 'ex_2_4_7',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Delicious',
                        optionsJson: JSON.stringify(['Delicioso', 'Rico', 'Bueno', 'Mal']),
                        answer: 'Delicioso',
                      },
                      {
                        id: 'ex_2_4_8',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Está muy ___ (It is very delicious)',
                        optionsJson: JSON.stringify([]),
                        answer: 'rico',
                      },
                    ],
                  },
                },
                {
                  id: 'lesson_2_5',
                  title: 'Practice: Review',
                  description: 'Review food vocabulary',
                  order: 5,
                  xpReward: 20,
                  type: 'practice',
                  exercises: {
                    create: [
                      {
                        id: 'ex_2_5_1',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Bread',
                        optionsJson: JSON.stringify(['Pan', 'Agua', 'Leche', 'Queso']),
                        answer: 'Pan',
                      },
                      {
                        id: 'ex_2_5_2',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Quiero ___ (I want water)',
                        optionsJson: JSON.stringify([]),
                        answer: 'agua',
                      },
                      {
                        id: 'ex_2_5_3',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'Apple',
                        optionsJson: JSON.stringify(['Manzana', 'Plátano', 'Naranja', 'Uva']),
                        answer: 'Manzana',
                      },
                      {
                        id: 'ex_2_5_4',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Me gusta el ___ (I like breakfast)',
                        optionsJson: JSON.stringify([]),
                        answer: 'desayuno',
                      },
                      {
                        id: 'ex_2_5_5',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'I am hungry',
                        optionsJson: JSON.stringify(['Tengo hambre', 'Tengo sed', 'Tengo frío', 'Tengo calor']),
                        answer: 'Tengo hambre',
                      },
                      {
                        id: 'ex_2_5_6',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: '___ un café, por favor (I would like a coffee, please)',
                        optionsJson: JSON.stringify([]),
                        answer: 'Quisiera',
                      },
                      {
                        id: 'ex_2_5_7',
                        type: 'mcq',
                        prompt: 'Choose the correct translation:',
                        question: 'The check, please',
                        optionsJson: JSON.stringify(['La cuenta, por favor', 'El menú, por favor', 'La mesa, por favor', 'El plato, por favor']),
                        answer: 'La cuenta, por favor',
                      },
                      {
                        id: 'ex_2_5_8',
                        type: 'fill_blank',
                        prompt: 'Complete the sentence:',
                        question: 'Está muy ___ (It is very delicious)',
                        optionsJson: JSON.stringify([]),
                        answer: 'rico',
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  });

  console.log('✅ Seeded course:', course.title);

  // French for Beginners
  const frenchCourse = await prisma.course.create({
    data: {
      id: 'course_french_101',
      title: 'French for Beginners',
      description: 'Learn the basics of French',
      language: 'French',
      units: {
        create: [
          {
            id: 'unit_fr_1',
            title: 'Unit 1: Greetings & Basics',
            description: 'Learn how to greet people and introduce yourself',
            order: 1,
            lessons: {
              create: [
                {
                  id: 'lesson_fr_1_1',
                  title: 'Greetings',
                  description: 'Learn basic greetings',
                  order: 1,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      { id: 'ex_fr_1_1_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Good morning', optionsJson: JSON.stringify(['Bonjour', 'Bonsoir', 'Merci', 'S\'il vous plaît']), answer: 'Bonjour', explanation: '"Bonjour" is used for hello/good morning.' },
                      { id: 'ex_fr_1_1_2', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Hello', optionsJson: JSON.stringify(['Bonjour', 'Au revoir', 'Merci', 'De rien']), answer: 'Bonjour', explanation: '"Bonjour" means hello.' },
                      { id: 'ex_fr_1_1_3', type: 'fill_blank', prompt: 'Complete the sentence:', question: '___ jour (Good morning)', optionsJson: JSON.stringify([]), answer: 'Bon', explanation: '"Bon jour" means good day.' },
                      { id: 'ex_fr_1_1_4', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Goodbye', optionsJson: JSON.stringify(['Bonjour', 'Au revoir', 'Bonsoir', 'Merci']), answer: 'Au revoir', explanation: '"Au revoir" means goodbye.' },
                      { id: 'ex_fr_1_1_5', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Comment ___ vous? (How are you?)', optionsJson: JSON.stringify([]), answer: 'allez', explanation: '"Comment allez-vous?" means How are you?' },
                      { id: 'ex_fr_1_1_6', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Thank you', optionsJson: JSON.stringify(['S\'il vous plaît', 'Merci', 'De rien', 'Bonjour']), answer: 'Merci', explanation: '"Merci" means thank you.' },
                      { id: 'ex_fr_1_1_7', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Enchanté ___ (Nice to meet you)', optionsJson: JSON.stringify([]), answer: 'de', explanation: '"Enchanté de vous rencontrer" means Nice to meet you.' },
                      { id: 'ex_fr_1_1_8', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Please', optionsJson: JSON.stringify(['Merci', 'S\'il vous plaît', 'De rien', 'Au revoir']), answer: 'S\'il vous plaît', explanation: '"S\'il vous plaît" means please.' },
                    ],
                  },
                },
                {
                  id: 'lesson_fr_1_2',
                  title: 'Introductions',
                  description: 'Learn how to introduce yourself',
                  order: 2,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      { id: 'ex_fr_1_2_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'My name is', optionsJson: JSON.stringify(['Je m\'appelle', 'Tu t\'appelles', 'Il s\'appelle', 'Nous nous appelons']), answer: 'Je m\'appelle', explanation: '"Je m\'appelle" means My name is.' },
                      { id: 'ex_fr_1_2_2', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je ___ Pierre (My name is Pierre)', optionsJson: JSON.stringify([]), answer: 'm\'appelle', explanation: '"Je m\'appelle" means My name is.' },
                      { id: 'ex_fr_1_2_3', type: 'mcq', prompt: 'Choose the correct translation:', question: 'What is your name?', optionsJson: JSON.stringify(['Comment vous appelez-vous?', 'Comment allez-vous?', 'Ça va?', 'D\'où venez-vous?']), answer: 'Comment vous appelez-vous?', explanation: '"Comment vous appelez-vous?" means What is your name?' },
                      { id: 'ex_fr_1_2_4', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je suis de ___ (I am from France)', optionsJson: JSON.stringify([]), answer: 'France', explanation: '"Je suis de France" means I am from France.' },
                      { id: 'ex_fr_1_2_5', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Where are you from?', optionsJson: JSON.stringify(['D\'où venez-vous?', 'Où habitez-vous?', 'Comment allez-vous?', 'Ça va?']), answer: 'D\'où venez-vous?', explanation: '"D\'où venez-vous?" means Where are you from?' },
                      { id: 'ex_fr_1_2_6', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'J\'ai ___ ans (I am twenty years old)', optionsJson: JSON.stringify([]), answer: 'vingt', explanation: '"J\'ai vingt ans" means I am twenty years old.' },
                      { id: 'ex_fr_1_2_7', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Nice to meet you', optionsJson: JSON.stringify(['Enchanté', 'À bientôt', 'Bonjour', 'Merci']), answer: 'Enchanté', explanation: '"Enchanté" means Nice to meet you.' },
                      { id: 'ex_fr_1_2_8', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Ravi de vous ___ (Pleased to meet you)', optionsJson: JSON.stringify([]), answer: 'rencontrer', explanation: '"Ravi de vous rencontrer" means Pleased to meet you.' },
                    ],
                  },
                },
                {
                  id: 'lesson_fr_1_3',
                  title: 'Numbers 1–10',
                  description: 'Learn numbers from one to ten',
                  order: 3,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      { id: 'ex_fr_1_3_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'One', optionsJson: JSON.stringify(['Un', 'Deux', 'Trois', 'Quatre']), answer: 'Un' },
                      { id: 'ex_fr_1_3_2', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Five', optionsJson: JSON.stringify(['Quatre', 'Cinq', 'Six', 'Sept']), answer: 'Cinq' },
                      { id: 'ex_fr_1_3_3', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Trois plus deux font ___ (Three plus two is five)', optionsJson: JSON.stringify([]), answer: 'cinq' },
                      { id: 'ex_fr_1_3_4', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Ten', optionsJson: JSON.stringify(['Huit', 'Neuf', 'Dix', 'Onze']), answer: 'Dix' },
                      { id: 'ex_fr_1_3_5', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Sept moins deux font ___ (Seven minus two is five)', optionsJson: JSON.stringify([]), answer: 'cinq' },
                      { id: 'ex_fr_1_3_6', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Eight', optionsJson: JSON.stringify(['Six', 'Sept', 'Huit', 'Neuf']), answer: 'Huit' },
                      { id: 'ex_fr_1_3_7', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Deux fois quatre font ___ (Two times four is eight)', optionsJson: JSON.stringify([]), answer: 'huit' },
                      { id: 'ex_fr_1_3_8', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Nine', optionsJson: JSON.stringify(['Sept', 'Huit', 'Neuf', 'Dix']), answer: 'Neuf' },
                    ],
                  },
                },
                {
                  id: 'lesson_fr_1_4',
                  title: 'Common Phrases',
                  description: 'Learn common everyday phrases',
                  order: 4,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      { id: 'ex_fr_1_4_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'How are you?', optionsJson: JSON.stringify(['Comment allez-vous?', 'Ça va?', 'Comment vous appelez-vous?', 'D\'où venez-vous?']), answer: 'Comment allez-vous?' },
                      { id: 'ex_fr_1_4_2', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je ___ bien (I am fine)', optionsJson: JSON.stringify([]), answer: 'vais', explanation: '"Je vais bien" means I am fine.' },
                      { id: 'ex_fr_1_4_3', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Excuse me', optionsJson: JSON.stringify(['Excusez-moi', 'Merci', 'S\'il vous plaît', 'De rien']), answer: 'Excusez-moi' },
                      { id: 'ex_fr_1_4_4', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je suis ___ (I am sorry)', optionsJson: JSON.stringify([]), answer: 'désolé', explanation: '"Je suis désolé" means I am sorry.' },
                      { id: 'ex_fr_1_4_5', type: 'mcq', prompt: 'Choose the correct translation:', question: "You're welcome", optionsJson: JSON.stringify(['Merci', 'De rien', 'S\'il vous plaît', 'Excusez-moi']), answer: 'De rien' },
                      { id: 'ex_fr_1_4_6', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'À ___ (See you later)', optionsJson: JSON.stringify([]), answer: 'bientôt', explanation: '"À bientôt" means See you soon.' },
                      { id: 'ex_fr_1_4_7', type: 'mcq', prompt: 'Choose the correct translation:', question: 'See you tomorrow', optionsJson: JSON.stringify(['À demain', 'À bientôt', 'Au revoir', 'À tout à l\'heure']), answer: 'À demain' },
                      { id: 'ex_fr_1_4_8', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Bonne ___ (Good night)', optionsJson: JSON.stringify([]), answer: 'nuit', explanation: '"Bonne nuit" means Good night.' },
                    ],
                  },
                },
                {
                  id: 'lesson_fr_1_5',
                  title: 'Practice: Review',
                  description: 'Review what you learned',
                  order: 5,
                  xpReward: 20,
                  type: 'practice',
                  exercises: {
                    create: [
                      { id: 'ex_fr_1_5_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Good morning', optionsJson: JSON.stringify(['Bonjour', 'Bonsoir', 'Bonne nuit', 'Bonjour']), answer: 'Bonjour' },
                      { id: 'ex_fr_1_5_2', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je ___ Marie (My name is Marie)', optionsJson: JSON.stringify([]), answer: 'm\'appelle' },
                      { id: 'ex_fr_1_5_3', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Thank you very much', optionsJson: JSON.stringify(['Merci beaucoup', 'De rien', 'S\'il vous plaît', 'Excusez-moi']), answer: 'Merci beaucoup' },
                      { id: 'ex_fr_1_5_4', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Comment ___ vous? (How are you?)', optionsJson: JSON.stringify([]), answer: 'allez' },
                      { id: 'ex_fr_1_5_5', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Nice to meet you', optionsJson: JSON.stringify(['Enchanté', 'À bientôt', 'Bonjour', 'Merci']), answer: 'Enchanté' },
                      { id: 'ex_fr_1_5_6', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je suis de ___ (I am from Belgium)', optionsJson: JSON.stringify([]), answer: 'Belgique' },
                      { id: 'ex_fr_1_5_7', type: 'mcq', prompt: 'Choose the correct translation:', question: 'See you later', optionsJson: JSON.stringify(['À bientôt', 'À demain', 'Au revoir', 'À tout à l\'heure']), answer: 'À bientôt' },
                      { id: 'ex_fr_1_5_8', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'J\'ai ___ ans (I am twenty years old)', optionsJson: JSON.stringify([]), answer: 'vingt' },
                    ],
                  },
                },
              ],
            },
          },
          {
            id: 'unit_fr_2',
            title: 'Unit 2: Food & Drinks',
            description: 'Learn vocabulary for food and drinks',
            order: 2,
            lessons: {
              create: [
                {
                  id: 'lesson_fr_2_1',
                  title: 'Food Basics',
                  description: 'Learn basic food vocabulary',
                  order: 1,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      { id: 'ex_fr_2_1_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Bread', optionsJson: JSON.stringify(['Pain', 'Eau', 'Lait', 'Fromage']), answer: 'Pain' },
                      { id: 'ex_fr_2_1_2', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Water', optionsJson: JSON.stringify(['Pain', 'Eau', 'Lait', 'Fromage']), answer: 'Eau' },
                      { id: 'ex_fr_2_1_3', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je veux du ___ (I want bread)', optionsJson: JSON.stringify([]), answer: 'pain' },
                      { id: 'ex_fr_2_1_4', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Milk', optionsJson: JSON.stringify(['Pain', 'Eau', 'Lait', 'Fromage']), answer: 'Lait' },
                      { id: 'ex_fr_2_1_5', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'J\'ai besoin d\'___ (I need water)', optionsJson: JSON.stringify([]), answer: 'eau' },
                      { id: 'ex_fr_2_1_6', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Cheese', optionsJson: JSON.stringify(['Pain', 'Eau', 'Lait', 'Fromage']), answer: 'Fromage' },
                      { id: 'ex_fr_2_1_7', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'J\'aime le ___ (I like cheese)', optionsJson: JSON.stringify([]), answer: 'fromage' },
                      { id: 'ex_fr_2_1_8', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Egg', optionsJson: JSON.stringify(['Œuf', 'Viande', 'Poisson', 'Poulet']), answer: 'Œuf' },
                    ],
                  },
                },
                {
                  id: 'lesson_fr_2_2',
                  title: 'Fruits & Vegetables',
                  description: 'Learn fruits and vegetables',
                  order: 2,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      { id: 'ex_fr_2_2_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Apple', optionsJson: JSON.stringify(['Pomme', 'Banane', 'Orange', 'Raisin']), answer: 'Pomme' },
                      { id: 'ex_fr_2_2_2', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Banana', optionsJson: JSON.stringify(['Pomme', 'Banane', 'Orange', 'Raisin']), answer: 'Banane' },
                      { id: 'ex_fr_2_2_3', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'J\'aime la ___ (I like the apple)', optionsJson: JSON.stringify([]), answer: 'pomme' },
                      { id: 'ex_fr_2_2_4', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Orange', optionsJson: JSON.stringify(['Pomme', 'Banane', 'Orange', 'Raisin']), answer: 'Orange' },
                      { id: 'ex_fr_2_2_5', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je veux une ___ (I want a banana)', optionsJson: JSON.stringify([]), answer: 'banane' },
                      { id: 'ex_fr_2_2_6', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Tomato', optionsJson: JSON.stringify(['Tomate', 'Laitue', 'Carotte', 'Pomme de terre']), answer: 'Tomate' },
                      { id: 'ex_fr_2_2_7', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'J\'ai besoin de ___ (I need tomatoes)', optionsJson: JSON.stringify([]), answer: 'tomates' },
                      { id: 'ex_fr_2_2_8', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Carrot', optionsJson: JSON.stringify(['Tomate', 'Laitue', 'Carotte', 'Pomme de terre']), answer: 'Carotte' },
                    ],
                  },
                },
                {
                  id: 'lesson_fr_2_3',
                  title: 'Meals',
                  description: 'Learn meal vocabulary',
                  order: 3,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      { id: 'ex_fr_2_3_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Breakfast', optionsJson: JSON.stringify(['Petit-déjeuner', 'Déjeuner', 'Dîner', 'Goûter']), answer: 'Petit-déjeuner' },
                      { id: 'ex_fr_2_3_2', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Lunch', optionsJson: JSON.stringify(['Petit-déjeuner', 'Déjeuner', 'Dîner', 'Goûter']), answer: 'Déjeuner' },
                      { id: 'ex_fr_2_3_3', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je vais ___ (I am going to have breakfast)', optionsJson: JSON.stringify([]), answer: 'petit-déjeuner' },
                      { id: 'ex_fr_2_3_4', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Dinner', optionsJson: JSON.stringify(['Petit-déjeuner', 'Déjeuner', 'Dîner', 'Goûter']), answer: 'Dîner' },
                      { id: 'ex_fr_2_3_5', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Qu\'est-ce que vous voulez pour le ___? (What do you want for lunch?)', optionsJson: JSON.stringify([]), answer: 'déjeuner' },
                      { id: 'ex_fr_2_3_6', type: 'mcq', prompt: 'Choose the correct translation:', question: 'I am hungry', optionsJson: JSON.stringify(['J\'ai faim', 'J\'ai soif', 'J\'ai froid', 'J\'ai chaud']), answer: 'J\'ai faim' },
                      { id: 'ex_fr_2_3_7', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'J\'ai ___ (I am thirsty)', optionsJson: JSON.stringify([]), answer: 'soif' },
                      { id: 'ex_fr_2_3_8', type: 'mcq', prompt: 'Choose the correct translation:', question: 'I want to eat', optionsJson: JSON.stringify(['Je veux manger', 'Je veux boire', 'Je veux dormir', 'Je veux étudier']), answer: 'Je veux manger' },
                    ],
                  },
                },
                {
                  id: 'lesson_fr_2_4',
                  title: 'Ordering Food',
                  description: 'Learn how to order food',
                  order: 4,
                  xpReward: 20,
                  type: 'lesson',
                  exercises: {
                    create: [
                      { id: 'ex_fr_2_4_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'I would like', optionsJson: JSON.stringify(['Je voudrais', 'Je veux', 'J\'ai besoin', 'J\'ai']), answer: 'Je voudrais' },
                      { id: 'ex_fr_2_4_2', type: 'fill_blank', prompt: 'Complete the sentence:', question: '___ un café, s\'il vous plaît (I would like a coffee, please)', optionsJson: JSON.stringify([]), answer: 'Je voudrais' },
                      { id: 'ex_fr_2_4_3', type: 'mcq', prompt: 'Choose the correct translation:', question: 'The check, please', optionsJson: JSON.stringify(['L\'addition, s\'il vous plaît', 'La carte, s\'il vous plaît', 'La table, s\'il vous plaît', 'L\'assiette, s\'il vous plaît']), answer: 'L\'addition, s\'il vous plaît' },
                      { id: 'ex_fr_2_4_4', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Pouvez-vous m\'apporter la ___? (Can you bring me the menu?)', optionsJson: JSON.stringify([]), answer: 'carte' },
                      { id: 'ex_fr_2_4_5', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Table', optionsJson: JSON.stringify(['Table', 'Chaise', 'Assiette', 'Verre']), answer: 'Table' },
                      { id: 'ex_fr_2_4_6', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Une ___ pour deux, s\'il vous plaît (A table for two, please)', optionsJson: JSON.stringify([]), answer: 'table' },
                      { id: 'ex_fr_2_4_7', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Delicious', optionsJson: JSON.stringify(['Délicieux', 'Bon', 'Bien', 'Mauvais']), answer: 'Délicieux' },
                      { id: 'ex_fr_2_4_8', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'C\'est très ___ (It is very delicious)', optionsJson: JSON.stringify([]), answer: 'bon', explanation: '"C\'est très bon" means It is very good/delicious.' },
                    ],
                  },
                },
                {
                  id: 'lesson_fr_2_5',
                  title: 'Practice: Review',
                  description: 'Review food vocabulary',
                  order: 5,
                  xpReward: 20,
                  type: 'practice',
                  exercises: {
                    create: [
                      { id: 'ex_fr_2_5_1', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Bread', optionsJson: JSON.stringify(['Pain', 'Eau', 'Lait', 'Fromage']), answer: 'Pain' },
                      { id: 'ex_fr_2_5_2', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'Je veux de l\'___ (I want water)', optionsJson: JSON.stringify([]), answer: 'eau' },
                      { id: 'ex_fr_2_5_3', type: 'mcq', prompt: 'Choose the correct translation:', question: 'Apple', optionsJson: JSON.stringify(['Pomme', 'Banane', 'Orange', 'Raisin']), answer: 'Pomme' },
                      { id: 'ex_fr_2_5_4', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'J\'aime le ___ (I like breakfast)', optionsJson: JSON.stringify([]), answer: 'petit-déjeuner' },
                      { id: 'ex_fr_2_5_5', type: 'mcq', prompt: 'Choose the correct translation:', question: 'I am hungry', optionsJson: JSON.stringify(['J\'ai faim', 'J\'ai soif', 'J\'ai froid', 'J\'ai chaud']), answer: 'J\'ai faim' },
                      { id: 'ex_fr_2_5_6', type: 'fill_blank', prompt: 'Complete the sentence:', question: '___ un café, s\'il vous plaît (I would like a coffee, please)', optionsJson: JSON.stringify([]), answer: 'Je voudrais' },
                      { id: 'ex_fr_2_5_7', type: 'mcq', prompt: 'Choose the correct translation:', question: 'The check, please', optionsJson: JSON.stringify(['L\'addition, s\'il vous plaît', 'La carte, s\'il vous plaît', 'La table', 'L\'assiette']), answer: 'L\'addition, s\'il vous plaît' },
                      { id: 'ex_fr_2_5_8', type: 'fill_blank', prompt: 'Complete the sentence:', question: 'C\'est très ___ (It is very delicious)', optionsJson: JSON.stringify([]), answer: 'bon' },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  });

  console.log('✅ Seeded course:', frenchCourse.title);
  console.log('✅ Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
